arb-dir: lib/src/config/l10n/arb
template-arb-file: intl_ru.arb
output-localization-file: home_localizations.dart
output-class: HomeLocalizations
synthetic-package: false
output-dir: lib/src/config/l10n/gen
