// Mocks generated by Mockito 5.4.6 from annotations
// in demo_project/test/features/login/presentation/cubit/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:demo_project/features/login/src/domain/repository/base_login_repository.dart'
    as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter/cupertino.dart' as _i3;
import 'package:logger_manager/src/app_logger.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInterceptor_0 extends _i1.SmartFake implements _i2.Interceptor {
  _FakeInterceptor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNavigatorObserver_1 extends _i1.SmartFake
    implements _i3.NavigatorObserver {
  _FakeNavigatorObserver_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseLoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLoginRepository extends _i1.Mock
    implements _i4.BaseLoginRepository {
  @override
  _i5.Future<({String accessToken, String refreshToken})> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i5.Future<({String accessToken, String refreshToken})>.value((
                  accessToken: _i6.dummyValue<String>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                  refreshToken: _i6.dummyValue<String>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                )),
            returnValueForMissingStub:
                _i5.Future<({String accessToken, String refreshToken})>.value((
                  accessToken: _i6.dummyValue<String>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                  refreshToken: _i6.dummyValue<String>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                )),
          )
          as _i5.Future<({String accessToken, String refreshToken})>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i7.AppLogger {
  @override
  _i2.Interceptor get apiLoggerInterceptor =>
      (super.noSuchMethod(
            Invocation.getter(#apiLoggerInterceptor),
            returnValue: _FakeInterceptor_0(
              this,
              Invocation.getter(#apiLoggerInterceptor),
            ),
            returnValueForMissingStub: _FakeInterceptor_0(
              this,
              Invocation.getter(#apiLoggerInterceptor),
            ),
          )
          as _i2.Interceptor);

  @override
  _i3.NavigatorObserver get routeLoggerObserver =>
      (super.noSuchMethod(
            Invocation.getter(#routeLoggerObserver),
            returnValue: _FakeNavigatorObserver_1(
              this,
              Invocation.getter(#routeLoggerObserver),
            ),
            returnValueForMissingStub: _FakeNavigatorObserver_1(
              this,
              Invocation.getter(#routeLoggerObserver),
            ),
          )
          as _i3.NavigatorObserver);

  @override
  void info(dynamic msg, {required Type? runtimeType}) => super.noSuchMethod(
    Invocation.method(#info, [msg], {#runtimeType: runtimeType}),
    returnValueForMissingStub: null,
  );

  @override
  void error({
    required Type? runtimeType,
    required String? operation,
    dynamic msg,
    Object? exc,
    StackTrace? st,
  }) => super.noSuchMethod(
    Invocation.method(#error, [], {
      #runtimeType: runtimeType,
      #operation: operation,
      #msg: msg,
      #exc: exc,
      #st: st,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void warning(dynamic msg, {required Type? runtimeType}) => super.noSuchMethod(
    Invocation.method(#warning, [msg], {#runtimeType: runtimeType}),
    returnValueForMissingStub: null,
  );
}
