// Mocks generated by Mockito 5.4.6 from annotations
// in demo_project/test/app/session/data/session_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:demo_project/core/api_client/src/session_observer.dart' as _i4;
import 'package:demo_project/core/local_storage/src/token_storage/base_token_storage.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BaseTokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseTokenStorage extends _i1.Mock implements _i2.BaseTokenStorage {
  MockBaseTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveTokens(String? accessToken, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [accessToken, refreshToken]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<({String accessToken, String refreshToken})?> getTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getTokens, []),
            returnValue:
                _i3.Future<
                  ({String accessToken, String refreshToken})?
                >.value(),
          )
          as _i3.Future<({String accessToken, String refreshToken})?>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SessionObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionObserver extends _i1.Mock implements _i4.SessionObserver {
  MockSessionObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<void> get onSessionExpired =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionExpired),
            returnValue: _i3.Stream<void>.empty(),
          )
          as _i3.Stream<void>);

  @override
  void emitSessionExpired() => super.noSuchMethod(
    Invocation.method(#emitSessionExpired, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
