name: logger_manager
description: "Logging infrastructure — AppLogger interface, Talker implementation, custom log types."
version: 0.0.1

publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Logger
  talker: ^5.1.13
  talker_dio_logger: ^5.1.13
  talker_flutter: ^5.1.13

  # Networking (for Interceptor type in AppLogger)
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.12.2
  injectable_generator: ^2.11.1

  # Linter
  flutter_lints: ^6.0.0
