name: ui_kit
description: "UI Kit — theme, widgets, design tokens."
version: 0.0.1

publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # UI
  equatable: ^2.0.8
  google_fonts: ^8.0.0
  skeletonizer: ^2.1.0+1

  # Core
  local_storage:
    path: ../local_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.12.2
  injectable_generator: ^2.11.1
  flutter_gen_runner: ^5.12.0

  # Linter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/body_states/

flutter_gen:
  output: lib/src/assets_gen/
  line_length: 100
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: false
    rive: false
    lottie: false
