// Mocks generated by Mockito 5.4.6 from annotations
// in demo_project/test/features/auth/data/repository/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:demo_project/features/auth/src/data/api/base_auth_api_service.dart'
    as _i3;
import 'package:demo_project/features/auth/src/data/model/login_request_dto.dart'
    as _i5;
import 'package:demo_project/features/auth/src/data/model/login_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseAuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseAuthApiService extends _i1.Mock
    implements _i3.BaseAuthApiService {
  @override
  _i4.Future<_i2.LoginResponseDto> login(_i5.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResponseDto>);
}
